config/routes.rb
Rsvp::Application.routes.draw do |map|
  resources :answers
  root :to => "answers#new"
  match "confirmado" => "answers#confirmado", :as => :confirmado
  match "nao_confirmado" => "answers#nao_confirmado", :as => :nao_confirmado

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates_uniqueness_of :email
  validates_presence_of :name, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  
  validates_inclusion_of :invite, :in => [true, false], :message => "Por favor, escolha Sim ou Não."
  attr_accessible :name, :email, :invite, :guests
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
  end
  
  def new
    @answer = Answer.new
  end
  
  def create
    @answer = Answer.new(params[:answer])
    if @answer.save
    SendRsvp.rsvp_confirmation(@answer).deliver
#     flash[:notice] = "Obrigado por preencher."
      if @answer.invite
        redirect_to confirmado_path
      else
        redirect_to nao_confirmado_path
      end
    else
      render :action => 'new'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/answers/confirmado.html.erb
Obrigado por confirmar sua presença! Estamos lhe aguardando na Confeitaria Colombo no dia 21/12/2010, às 18h. Até breve!

app/views/answers/index.html.erb
<% title "Answers" %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Invite</th>
    <th>Guests</th>
  </tr>
  <% for answer in @answers %>
    <tr>
      <td><%= answer.name %></td>
      <td><%= answer.email %></td>
      <td><%= answer.invite %></td>
      <td><%= answer.guests %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Answer", new_answer_path %></p>

app/views/answers/nao_confirmado.html.erb
Lamentamos que não possa comparecer. Caso mude de ideia, ligue para <strong>(22) 2757 1408</strong> ou <strong>(21) xxx-xxx</strong>

app/views/answers/new.html.erb
Nós, Vanelli e Ari, desejamos muito que você compareça às nossas Bodas de Prata. Pedimos que confirme a participação, ou em caso de não poder comparecer, que marque 'Não' no local indicado.

<% title "RSVP para Bodas de Vanelli e Ari" %>

<%= form_for @answer do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label 'Nome' %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label 'E-mail' %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label 'Comparecerá ao evento?' %><br />
    <%= f.radio_button :invite, 1 %> Sim     <%= f.radio_button :invite, 0 %> Não
  </p>
  <p>
    <%= f.label 'Número de convidados' %><br />
    <%= f.text_field :guests %>
  </p>
  <p><%= f.submit 'Enviar RSVP'%></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/send_rsvp/rsvp_confirmation.text.erb
<% if @answer.invite then -%>
<%= "#{@answer.name} respondeu ao RSVP. Ele levará #{@answer.guests} convidados. " %>
<% else -%>
<%= "#{@answer.name} não comparecerá ao evento." %>
<% end -%>